### PR TITLE
Add support for function A.B syntax with hoisting

### PR DESCRIPTION
**Pull request by psrok1**
There are few malware samples in the wild that are using `function A.prototype.B()` syntax. Unfortunately, current rewrite by simple substitution doesn't work, because of two things:
- sometimes semicolon is missing at the end of rewrited declaration (pretty fixable anyway)
- **function hoisting** (uh, very annoying... I've found it was noticed yet in #11)

e.g. for this sample: https://malwr.com/analysis/ZjdlZDEzMWVjNWM1NDgxYjgxNjYzYzQwYTM4NzRhNDY/
(download link doesn't work, but code still can be extracted from `Static Analysis -> Strings`)

I've got bunch of errors: https://gist.github.com/psrok1/a053fcff6151622160af5c700aa7d48b

In this PR I've added some features which should fix that issue:

- Acorn plugin, which is able to parse function identifiers like `foo.bar` as `MemberExpressions`
- Transformation from `function foo.bar` statement to `foo.bar = function` expression using `traverse`.
- AST reordering to emulate hoist behavior within a scope

It was tested a bit, and it works pretty well for me, but I'm still not sure about some unexpected side effects. Anyway, for this test case (https://gist.github.com/psrok1/77cf2aad0920ad4235cfb77d4e8aaf36), it gives the same output on patched box-js and original Windows Script Host.

### CODE REVIEW

**Comment by CapacitorSet** [comment]
I see you're still making fixes; leave a message when you're ready for merging.

I appreciate the pull request, but I haven't had the time to look at the code in detail - I'll do that in a few hours.

**Comment by psrok1** [comment]
Yes, hooking these Acorn routines is more tricky than I thought. I'll test it on broader set of droppers and notify when it will be done.

**Comment by psrok1** [comment]
Ok, I've done some research and found that `A.prototype.B` can also occur in function expressions, not only declarations. The second thing is that function expressions are also hoisted in JScript.

After patch - this code:
```javascript
"Hello World!".global_func();
var a = ["alpha", "beta", function String.prototype.global_func(arg_a, arg_b) { WScript.echo(this); }, "WScript"];
```
is now rewritten to this form:
```javascript
String.prototype.global_func = function (arg_a, arg_b) {
    WScript.echo(this);
};
'Hello World!'.global_func();
var a = ['alpha', 'beta', String.prototype.global_func, 'WScript' ];
```

It's not great but works in most cases. After the test on 1.5k dropper samples, 30+ more were successfully analyzed. By the time, PR is ready to merge and improves box-js a bit (including #32 issue).

**Comment by CapacitorSet** [comment]
Thanks for your contribution! It's certainly not a perfect implementation, since it will break if the function body uses closures, but it ought to work fine for most samples. Good job!

**Comment by CapacitorSet** [comment]
By the way, there was a small bug: if a tree contained null elements (eg. `var foo = [1, 2, , , 3]`), it would crash at the line `if (el.hoist)` ([link](https://github.com/CapacitorSet/box-js/pull/31/files#diff-7e3ad6eaa0dbf561a6b14eaba40b3b45R467)). No worries, however, I fixed it.

**Pull request merged**
